services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - 8888:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      DYNAMIC_CONFIG_ENABLED: true

  user-service:
    build:
      dockerfile: user-service.Dockerfile
    container_name: user-service
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5433/UserServiceDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Griffith
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - user-service-db
      - kafka
    ports:
      - 8082:8082

  api-gateway:
    build:
      dockerfile: api-gateway.Dockerfile
    container_name: api-gateway
    environment:
      - SERVER_PORT=8080
      - SERVICE_ACCOUNT_URL=http://localhost:8081/api/account-service
      - SERVICE_USER_URL=http://localhost:8082/api/user-service
      - SERVICE_AUTH_URL:http://localhost:8083/api/auth-service
    ports:
      - 8080:8080

  auth-service:
    build:
      dockerfile: auth-service.Dockerfile
    container_name: auth-service
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5434/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Griffith
    depends_on:
      - auth-service-db
    ports:
      - 8083:8083

  account-service:
    build:
      dockerfile: account-service.Dockerfile
    container_name: account-service
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5435/AccountServiceDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Griffith
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - account-service-db
      - kafka
    ports:
      - 8081:8081

  user-service-db:
    image: postgres:15-alpine
    container_name: 'UserServiceDB'
    environment:
      environment:
      POSTGRES_DB: "UserServiceDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Griffith"
    ports:
      - "5433:5432"

  account-service-db:
    image: postgres:15-alpine
    container_name: 'AccountServiceDB'
    environment:
      POSTGRES_DB: "AccountServiceDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Griffith"
    ports:
      - "5435:5432"

  auth-service-db:
    image: postgres:15-alpine
    container_name: 'AuthServiceDB'
    environment:
        POSTGRES_DB: "AuthServiceDB"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "Griffith"
    ports:
      - "5434:5432"

